### ISSUE TITLE
Merging pdfs of version 1.5 not working

### ISSUE THREAD

**Issue by ewallteam** [hanneskod/libmergepdf#34] opened 2019-03-25 10:21 UTC
Hi, 
I am using PDF version 1.5. Unable to merge them, and got the below error.

Fatal error: Uncaught Exception: TCPDF_PARSER ERROR: decodeFilterFlateDecode: invalid code in /libmergepdf/vendor/tecnickcom/tcpdf/include/tcpdf_filters.php:474 Stack trace: 
#0 /libmergepdf/vendor/tecnickcom/tcpdf/include/tcpdf_filters.php(359): TCPDF_FILTERS::Error('decodeFilterFla...') 
#1 /libmergepdf/vendor/tecnickcom/tcpdf/include/tcpdf_filters.php(94): TCPDF_FILTERS::decodeFilterFlateDecode('b\x8F\\\xBEW)ccQ\x0F\x06E\x83!j...') 
#2 /libmergepdf/vendor/rafikhaceb/tcpdi/tcpdi_parser.php(1158): TCPDF_FILTERS::decodeFilter('FlateDecode', 'b\x8F\\\xBEW)ccQ\x0F\x06E\x83!j...') 
#3 /libmergepdf/vendor/rafikhaceb/tcpdi/tcpdi_parser.php(1046): tcpdi_parser->decodeStream(Array, 'b\x8F\\\xBEW)ccQ\x0F\x06E\x83!j...') 
#4 /libmergepdf/vendor/rafikhaceb/tcpdi/tcpdi_parser.php(1082 in /libmergepdf/src/Driver/TcpdiDriver.php on line 52

**Comment by hanneskod** [comment] 2019-03-27 20:11
Not a very helpful exception message =) And of course its even harder to say anything without the input that triggered the exception. I am however no pdf wizz and would like to direct this issue to tcpdi. Not sure though how maintained or stable actually tcpdi is. There is a number of versions in the wild. Problematic..

Could you attach the pdf you are trying to merge so that I can reproduce?

**Comment by hanneskod** [comment] 2019-04-23 19:51
Closing as there is no development..

**Closed by hanneskod** 2019-04-23 19:51 UTC

**Comment by rohantapiyawala** [comment] 2020-09-30 14:41
Hi I have a similar issue for merging pdf with my system data to generate a final pdf. Can you please help its an urgent issue.

**Comment by kaystrobach** [comment] 2020-09-30 15:04
maybe stop complaining and ask for payed support ...

**Comment by rohantapiyawala** [comment] 2020-09-30 15:14
@kaystrobach Dude no one is complaining. There is an issue and we are reporting and if it requires paid support, I dont mind that, but I would rather have the repository owner write back to me, than a dumbass wanna be who cant even spell "paid".

**Comment by kaystrobach** [comment] 2020-09-30 16:21
As @hanneskod helped me a lot with his project i try to help him with issues.

Most of the time the comments are not helpful - as yours is, as there is no isolated test case.
Other problems are related to underlying libraries like the mentioned tcpdi or fpdf.

With the information you provided no one will be able to help you.
The tone you used will kill the remaining motivation - atleast for me.

Have a nice day

**Comment by rohantapiyawala** [comment] 2020-09-30 16:39
@kaystrobach Yeah I agree the tone or the conversation that you have started here is very demotivating and discouraging for young developers and others to even put any new issue requests here. 

No one was/is complaining, as we have officially put in request and as I said in my earlier comment, if the repository owner requests for more information or personalized paid support, Im all in support for that. 

Yes, I don't expect any motivation/support from you cause your tone was very demeaning to me and Im sure others will think twice before posting. 

Be the part of the solution, not cause of the problem.

**Comment by kaystrobach** [comment] 2020-09-30 16:59
So lets be constructive:

* can you isolate the issue to a minimal pdf (one page or so?
* can you relate the problem to the creator (software, webservice) of the pdf (adobe, foxit, ...)
* can you isolate it to a specific pdf version?

Can you post the pdf info here, as we have some known issues with newer pdf versions.

Can you add more context of the exception via trace or more descriptive debug output? What code (which is known to be invalid) was supplied to the function etc.

**Comment by kaystrobach** [comment] 2020-09-30 17:03
If the problem is related to a new pdf version https://github.com/xthiago/pdf-version-converter might be an option. Then you can use the merger with the resulting pdfs.

**Comment by hanneskod** [comment] 2020-10-22 20:05
Hi @rohantapiyawala and sorry for the late reply. Sad to read that you are demotivated by this thread. It's easy to use unnecessarily harsh words in written text, I think @kaystrobach reacted a bit to fast. In all honesty. In all honesty, so did you.

I would also like to say that I appreciate that @kaystrobach takes to time to answer to these issues when I cant.

As for the tecnical I am afraid my original answer to @ewallteam still applies. 1) It's impossible to comment on the issue without being able to reproduce localy. 2) This is a tcpdi issue, and I lift my hands from that. The only long term solution is to replace tcpdi with something more mantained and more stable. Suggestions are appreciated.

As my response time suggests I am not availiable for paid support..

**Comment by rohantapiyawala** [comment] 2020-10-22 21:57
Hey Hanneskod/Libmergepdf,

Thanks for your reply. I don't know who kaystrobach
<https://github.com/kaystrobach> is and whether he represents you or not. I
tried contacting you via email and comment but couldn't get your response
in time for the release of my project. So I opted for some other library.
As I mentioned in my comment I couldn't not share the PDF publicly as the
PDF content had sensitive information, but could have mailed you had you
replied.

No worries, in any case I was able to solve the issue and figure out
another solution.

Thank you for replying back and hope you have a great weekend ahead.

~Rohan

 As I said the PDF file in question could not be shared publicly though

**Comment by dhcmega** [comment] 2021-01-05 13:11
@rohantapiyawala do you mind sharing how you solved it?

**Comment by rohantapiyawala** [comment] 2021-01-05 13:15
@dhcmega As the pdf uploaded by the users are not consistent, I had to convert those to a particular format using ghostscript. Convert my database info to that specific pdf and then merge them. This works for me, but Adobe might give you issue, if there is any inconsistency with Fonts or Formatting (like using non standard fonts) 

Hope this helps.

**Comment by zettabyte84** [comment] 2022-03-01 04:08
I got the same error. the thing that I aware is, this pdf is password protected in edit mode. 

![image](https://user-images.githubusercontent.com/1235130/156102886-52fc6c56-5e63-418a-9918-d18dc1ef9972.png)

Is there anyway to solve this for merging pdf?
