### ISSUE TITLE
iio\libmergepdf\Merger not found

### ISSUE THREAD

**Issue by aderaHenry** [hanneskod/libmergepdf#33] opened 2019-01-03 05:54 UTC
I get this error `Fatal error: Uncaught Error: Class 'iio\libmergepdf\Merger' not found in...` while the class is actually there. What could be the problem?

Steps to reproduce:

1. Install library via composer
2. Import the paths and create an instance of the class Merger
3. Execute.

**Comment by hanneskod** [comment] 2019-01-03 23:15
Hi and thanx for reporting. I am however not able to reproduce this. Could you be more concrete? Possibly post the smallest possible failing script?

**Comment by hanneskod** [comment] 2019-01-14 08:13
Closing as this seems unrelated.

**Closed by hanneskod** 2019-01-14 08:13 UTC
